name: main cicd pipeline
on:
    workflow_dispatch:
    push:
        branches:
        - 'main'
    pull_request:
        branches:
        - 'main'

jobs:
    test:
        runs-on: ubuntu-latest
        environment: development
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: install dependencies
              run: npm install
            - name: run tests
              run: npm run tests
    
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: checkout code
              uses: actions/checkout@v4
            - name: configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ap-southeast-2
            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
            - name: Build, tag, and push image to Amazon ECR
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                ECR_REPOSITORY: captainborisTechSscrum
              run: |
                docker build -t $ECR_REGISTRY/ECR_REPOSITORY:$GITHUB_RUN_NUMBER .
                docker push $ECR_REGISTRY/ECR_REPOSITORY:$GITHUB_RUN_NUMBER










            # - name: checkout code
            #   uses: actions/checkout@v4
            # - name: install dependencies
            #   run: npm install
            # - name: build app
            #   run: npm run build
            # - name: docker build image
            #   run: docker build -t myapp .